import React from 'react'

const Head = () => {
  return (
    <>
    <title>Nextjs Kursu</title>
    <meta name='description' content='Generated by create next app'/>
    <link rel='icon' href='favicon'/>
    </>
  )
}

export default Head